
name: monimate
description: MoniMate â€“ Offline Expense Tracker (Flutter template)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  uuid: ^4.4.0
  path_provider: ^2.1.2
  csv: ^6.0.0
  share_plus: ^10.0.2
  get_storage: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
